import type { CopyKey } from "./types";

const copy: Record<"en" | "zh", Record<CopyKey, string>> = {
  en: {
    privateCopilot: "Private task co-pilot",
    session: "Session",
    settings: "Settings",
    runningSideTab: "别meow鱼 is running in the side tab.",
    handoffBody: "You can close or ignore this main window. The current step and any gentle prompts will stay in the slim sidebar.",
    endSession: "End session",
    lockInMode: "Lock-in Mode",
    lockInModeHint: "When 别meow鱼 detects you've drifted off-task, the cat gives a visible warning first, then blocks distractions if you keep drifting.",
    lockInBlockerTitle: "别meow鱼 is watching",
    lockInBack: "I'm back",
    lockInWarningTitle: "The cat is watching.",
    lockInWarningBody: "Return to the current step before 别meow鱼 blocks the distraction.",
    physicalTask: "Physical/off-screen task",
    topPriority: "Top priority",
    startOnThis: "Start on this now",
    addTask: "Add a task...",
    tasksDueToday: "tasks due today — I'll sort by deadline.",
    nothingUrgent: "Nothing urgent right now — starting early is great!",
    pauseSession: "Pause session",
    resumeSession: "Resume session",
    pausedTitle: "Session paused.",
    pausedBody: "I'll hold this spot. Capture and reminders are paused until you resume.",
    ready: "Ready when you are",
    goal: "Goal",
    taskType: "Task type",
    mode: "Mode",
    screenshotNotice: "别meow鱼 captures screenshots during a session and stores them locally on this device for demo/debugging. You can delete session data from Settings.",
    startSession: "Start Session",
    currentProvider: "Current provider",
    nextStep: "Next step",
    sessionComplete: "Session complete.",
    currentStep: "Current step",
    noSession: "No session is active.",
    done: "Done",
    thinking: "I'm thinking",
    cancelThinking: "Cancel thinking pause",
    delay: "5 more minutes",
    thinkingHold: "Got it. I'll hold this step while you think.",
    routine: "Routine",
    repeatRoutine: "Repeat routine task",
    routineEvery: "Repeat every",
    routineNext: "Next routine",
    waitingRoutineTitle: "Waiting for the next scheduled routine.",
    waitingRoutineBody: "I'll bring it back to priority 1 when it is time.",
    breakReminders: "Break reminders",
    breakReminderEvery: "Remind every",
    breakDuration: "Break length",
    breakTime: "Break time",
    breakEndsIn: "Break ends in",
    getBackToWork: "Get back to work",
    nextBreak: "Next break",
    pastDeadlineTitle: "Past deadline",
    pastDeadlineBody: "This time has already passed. Confirm it if this is the deadline you meant to keep.",
    keepPastDeadline: "Keep this deadline",
    nextPhysical: "No rush. When you're ready, the next physical action is:",
    completePrompt: "This step looks complete. Mark it done?",
    markDone: "Mark Done",
    keepWorking: "Keep Working",
    noAppChanges: "No app changes yet.",
    stateOnTask: "On task",
    stateProgress: "Progress",
    stateProductiveDrift: "Possibly related",
    stateUnproductiveDrift: "Away",
    stateStuck: "Stuck",
    stateThinking: "Thinking",
    stateUnknown: "Holding",
    language: "Language",
    english: "English",
    mandarin: "Mandarin",
    aiProvider: "AI provider",
    deepseekKey: "DeepSeek API key",
    deepseekModel: "DeepSeek model",
    detectionInterval: "Detection interval",
    stuckThreshold: "Stuck threshold",
    driftThreshold: "Drift threshold",
    thinkingPause: "Thinking pause",
    panelOpacity: "Panel opacity",
    storeScreenshots: "Store screenshots locally",
    privacyNotice: "DeepSeek analysis may send screen/session context to the configured API. Screenshots stay local unless you explicitly change the implementation.",
    openScreenshotFolder: "Open screenshot folder",
    deleteData: "Delete all local session data",
    viewPlan: "View plan",
    calendar: "Calendar",
    viewLog: "Session log",
    history: "History",
    hotkeyHint: "Win+Shift+N toggles the sidebar.",
    bannedSites: "Banned websites",
    bannedSitesEnabled: "Intrusive banned-site overlay",
    bannedSitesHelp: "One domain per line. 别meow鱼 detects these locally from the active browser window when Windows exposes the page URL or title.",
    bannedSiteTitle: "Leave this site.",
    bannedSiteBody: "This site is on your banned list for this session. Close it or switch back to the task now.",
    bannedSiteBody2: "You came back. Close it and refocus.",
    bannedSiteBody3: "Third time. Close this tab and don't come back.",
    bannedSiteAction: "Return to the current task:",
    soundEnabled: "Sound alert on detection",
    endSessionConfirm: "You still have steps to go. End the session anyway?",
    endSessionConfirmYes: "Yes, end it",
    endSessionConfirmNo: "Keep going",
    replanSession: "Re-plan from here",
    replanning: "Regenerating plan…",
    inboxTitle: "Inbox",
    inboxEmpty: "No action items found",
    inboxFetch: "Scan inbox",
    inboxFetching: "Scanning...",
    inboxConnect: "Connect Gmail",
    inboxDisconnect: "Disconnect",
    inboxPromote: "Add to session",
    inboxAdded: "Added",
    inboxDismiss: "Dismiss",
    inboxReminderHint: "Pick a reminder before adding.",
    suggestedReminder: "Suggested slot",
    inboxWillSchedule: "Will add to schedule",
    inboxChangeSlot: "Activity time",
    inboxReminderToggle: "Add reminder",
    inboxReminderAt: "Reminder time",
    inboxNoReminder: "No reminder",
    inboxConnected: "Connected",
    inboxNotConnected: "Not connected",
    inboxSetupHint: "Enter your Google OAuth Client ID in Settings to connect Gmail.",
    inboxNoActivePlan: "No active plan right now. Make a plan from the main page first, then come back to add inbox items to the session.",
    quickNotes: "Quick notes",
    notePlaceholder: "Something to remember or add to the plan...",
    noteReminder: "Reminder",
    addNote: "Add to plan",
    reminderRequired: "Choose a reminder time first.",
    reminders: "Reminders",
    startNow: "Start now",
    remindLater: "Remind later",
    setReminder: "Set reminder",
    connectors: "Connectors",
    googleClientId: "Google Client ID",
    googleClientIdHint: "Create a Desktop app OAuth client at console.cloud.google.com",
    googleClientSecret: "Google Client Secret",
    googleClientSecretHint: "Required for some Google OAuth client types; leave blank if your client does not have one.",
    saveGoogleOAuth: "Save Google OAuth",
    elevenLabsApiKey: "ElevenLabs API key",
    elevenLabsVoiceId: "ElevenLabs voice ID",
    elevenLabsVoiceHint: "Pick a voice from the ElevenLabs voice library.",
    voiceCoach: "Voice coach",
    voiceAddElevenLabs: "Add ElevenLabs API key and voice ID in Settings",
    voiceStopListening: "Stop listening",
    voiceStartCoach: "Start voice coach",
    voiceListeningStop: "Listening... press again to stop",
    voiceThinking: "Thinking...",
    voiceSpeakingReply: "Speaking reply",
    voiceAddElevenLabsSettings: "Add ElevenLabs key in Settings",
    voiceAskCoach: "Ask voice coach (Alt+M)",
    voiceListening: "Listening..."
  },
  zh: {
    privateCopilot: "私人任务辅助",
    session: "会话",
    settings: "设置",
    runningSideTab: "别meow鱼 正在侧边栏运行。",
    handoffBody: "你可以关闭或忽略主窗口。当前步骤和温和提示会留在右侧小栏里。",
    endSession: "结束会话",
    lockInMode: "锁定模式",
    lockInModeHint: "当 别meow鱼 检测到你偏离任务时，猫咪会先明显提醒；如果继续走神，就会拦截分心内容。",
    lockInBlockerTitle: "别meow鱼 正在看着你",
    lockInBack: "我回来了",
    lockInWarningTitle: "猫咪正在看着你。",
    lockInWarningBody: "回到当前步骤，否则 别meow鱼 会拦截分心内容。",
    physicalTask: "线下/不在屏幕上的任务",
    topPriority: "最高优先级",
    startOnThis: "现在就开始",
    addTask: "添加任务...",
    tasksDueToday: "今天到期的任务 — 我会按截止时间排序。",
    nothingUrgent: "暂时没有紧急事项 — 提早开始很好！",
    pauseSession: "暂停会话",
    resumeSession: "继续会话",
    pausedTitle: "会话已暂停。",
    pausedBody: "我会保留当前位置。截图和提醒会暂停，直到你继续。",
    ready: "准备好时开始",
    goal: "目标",
    taskType: "任务类型",
    mode: "模式",
    screenshotNotice: "别meow鱼 会在会话期间截图，并只保存在本设备用于演示/调试。你可以在设置中删除本地数据。",
    startSession: "开始会话",
    currentProvider: "当前提供方",
    nextStep: "下一步",
    sessionComplete: "会话已完成。",
    currentStep: "当前步骤",
    noSession: "当前没有活动会话。",
    done: "完成",
    thinking: "我在思考",
    cancelThinking: "取消思考暂停",
    delay: "再给我 5 分钟",
    thinkingHold: "收到。我会先帮你保留这一步。",
    routine: "例行任务",
    repeatRoutine: "重复例行任务",
    routineEvery: "重复间隔",
    routineNext: "下次例行任务",
    waitingRoutineTitle: "正在等待下一次例行任务。",
    waitingRoutineBody: "到时间时，我会把它提到优先级 1。",
    breakReminders: "休息提醒",
    breakReminderEvery: "提醒间隔",
    breakDuration: "休息时长",
    breakTime: "休息时间",
    breakEndsIn: "休息剩余",
    getBackToWork: "回到工作",
    nextBreak: "下次休息",
    pastDeadlineTitle: "截止时间已过",
    pastDeadlineBody: "这个时间已经过去。如果这是你想保留的截止时间，请确认。",
    keepPastDeadline: "保留这个截止时间",
    nextPhysical: "不急。准备好时，下一步身体动作是：",
    completePrompt: "这一步看起来已完成。要标记完成吗？",
    markDone: "标记完成",
    keepWorking: "继续处理",
    noAppChanges: "还没有应用切换记录。",
    stateOnTask: "在任务中",
    stateProgress: "有进展",
    stateProductiveDrift: "可能相关",
    stateUnproductiveDrift: "已离开",
    stateStuck: "卡住",
    stateThinking: "思考中",
    stateUnknown: "保留中",
    language: "语言",
    english: "英语",
    mandarin: "中文",
    aiProvider: "AI 提供方",
    deepseekKey: "DeepSeek API 密钥",
    deepseekModel: "DeepSeek 模型",
    detectionInterval: "检测间隔",
    stuckThreshold: "卡住阈值",
    driftThreshold: "偏离阈值",
    thinkingPause: "思考暂停",
    panelOpacity: "侧栏透明度",
    storeScreenshots: "本地保存截图",
    privacyNotice: "DeepSeek 分析可能会把屏幕/会话上下文发送到配置的 API。截图仍保存在本地，除非你明确修改实现。",
    openScreenshotFolder: "打开截图文件夹",
    deleteData: "删除所有本地会话数据",
    viewPlan: "查看计划",
    calendar: "日历",
    viewLog: "会话日志",
    history: "历史",
    hotkeyHint: "Win+Shift+N 可切换侧栏。",
    bannedSites: "禁止网站",
    bannedSitesEnabled: "强提醒禁止网站覆盖层",
    bannedSitesHelp: "每行一个域名。Windows 暴露当前浏览器 URL 或标题时，别meow鱼 会在本地检测这些网站。",
    bannedSiteTitle: "离开这个网站。",
    bannedSiteBody: "这个网站在你的禁止列表里。现在关闭它，或切回当前任务。",
    bannedSiteBody2: "你又回来了。关掉它，重新集中注意力。",
    bannedSiteBody3: "第三次了。关掉这个标签页，别再来了。",
    bannedSiteAction: "回到当前任务：",
    soundEnabled: "检测到时播放声音提醒",
    endSessionConfirm: "你还有步骤未完成，确定要结束会话吗？",
    endSessionConfirmYes: "是的，结束",
    endSessionConfirmNo: "继续进行",
    replanSession: "从这里重新规划",
    replanning: "正在重新生成计划…",
    inboxTitle: "收件箱",
    inboxEmpty: "没有待处理事项",
    inboxFetch: "扫描邮件",
    inboxFetching: "扫描中...",
    inboxConnect: "连接 Gmail",
    inboxDisconnect: "断开连接",
    inboxPromote: "加入任务",
    inboxAdded: "已加入",
    inboxDismiss: "忽略",
    inboxReminderHint: "加入前先选择提醒时间。",
    suggestedReminder: "建议时间段",
    inboxWillSchedule: "将加入日程",
    inboxChangeSlot: "活动时间",
    inboxReminderToggle: "添加提醒",
    inboxReminderAt: "提醒时间",
    inboxNoReminder: "无提醒",
    inboxConnected: "已连接",
    inboxNotConnected: "未连接",
    inboxSetupHint: "请在设置中输入 Google OAuth 客户端 ID 以连接 Gmail。",
    inboxNoActivePlan: "当前没有活动计划。请先从主页创建计划，然后回来把邮件事项加入会话。",
    quickNotes: "快速笔记",
    notePlaceholder: "临时想到的事情，或想加入计划的想法...",
    noteReminder: "提醒",
    addNote: "加入计划",
    reminderRequired: "请先选择提醒时间。",
    reminders: "提醒",
    startNow: "现在开始",
    remindLater: "稍后提醒",
    setReminder: "设置提醒",
    connectors: "连接器",
    googleClientId: "Google 客户端 ID",
    googleClientIdHint: "在 console.cloud.google.com 创建桌面应用 OAuth 客户端",
    googleClientSecret: "Google 客户端密钥",
    googleClientSecretHint: "某些 Google OAuth 客户端类型需要；如果你的客户端没有密钥可留空。",
    saveGoogleOAuth: "保存 Google OAuth",
    elevenLabsApiKey: "ElevenLabs API 密钥",
    elevenLabsVoiceId: "ElevenLabs 声音 ID",
    elevenLabsVoiceHint: "从 ElevenLabs 声音库选择一个声音。",
    voiceCoach: "语音教练",
    voiceAddElevenLabs: "请先在设置中添加 ElevenLabs API 密钥和声音 ID",
    voiceStopListening: "停止聆听",
    voiceStartCoach: "启动语音教练",
    voiceListeningStop: "正在聆听... 再按一次停止",
    voiceThinking: "正在思考...",
    voiceSpeakingReply: "正在语音回复",
    voiceAddElevenLabsSettings: "请在设置中添加 ElevenLabs 密钥",
    voiceAskCoach: "询问语音教练 (Alt+M)",
    voiceListening: "正在聆听..."
  }
};

export function useCopy(language: "en" | "zh") {
  return (key: CopyKey) => copy[language][key];
}
